# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField()),
            ],
        ),
    ]
